# To run this play-book
# Pre-requisite: aws configure  , git clone https://github.com/ManiReddy-1808/ansible-roles-roboshop.git
# ansible-playbook -i localhost,   -e "instances=['mongodb','catalogue','redis','user','cart','mysql','shipping','rabbitmq','payment','frontend']" -e action=create create-ec2.yaml

- name: create EC2 and Route53 records
  hosts: all  # To run :: ansible-playbook -i localhost, create-ec2.yaml
  connection: local
  vars:
    sg_id: sg-04303efbdaed5c6f9
    ami_id: ami-0220d79f3f480ecf5
    domain_name: dawsmani.site
    env: dev
    action: create  # default action is: create
    instances: # List 
    - mongodb
    - catalogue
  tasks:
  - name: instal python dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  ### CREATE ###
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}" # To display Instance name at instances UI
      # wait: false # (don't use wait --> here because we need to create r53 records with private IP)
      tags:  # To know about other what this project is about.
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}" 
    loop: "{{ instances }}"  # 1st time mongodb comes here
    register: ec2_output
    when: action == "create"

  - name: print output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"  #item is entire result[] of 0th index
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # frontend-dev.dawsmani.site, mongodb-dev.dawsmani.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"  # 1st Instance index is 0
      wait: false
      overwrite: true # replace existing record with new
    loop: "{{ ec2_output.results }}" # list 
    when: action == "create"

  - name: create r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.dawsmani.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"  # 1st Instance index is 0
      wait: false # Perform quick don't wait 
      overwrite: true # replace existing record with new
    loop: "{{ ec2_output.results }}"
    when:  # List of and
    - item.item == "frontend"
    - action == "create"

  ### DESTROY ###

  - name: delete r53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.dawsmani.site
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when:  # and condition
    - item == "frontend"
    - action == "destroy"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.dawsmani.site
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
      wait: false # Perform quick don't wait 
    loop: "{{ instances }}"
    when: action == "destroy"