- name: "Configure {{ component }} Server"
  hosts: "{{ component }}"
  become: yes
  roles:
  - "{{ component }}"


# To run mongodb: ansible-playbook -i inventory -e component=mongodb create-ec2.yaml